[build]
builder = "NIXPACKS"

[phases.build]
[[phases.build.cmds]]
command = "npx prisma generate"

[[phases.build.cmds]]
command = "npm run build"

[variables]
NODE_VERSION = "22"
NODE_ENV = "production"